"""Initial migration

Revision ID: 7af39103eace
Revises: 
Create Date: 2025-10-30 22:28:18.221618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af39103eace'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aisles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aisles_id'), 'aisles', ['id'], unique=False)
    op.create_index(op.f('ix_aisles_name'), 'aisles', ['name'], unique=True)
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aisle_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aisle_id'], ['aisles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aisle_id', 'code', name='uq_aisle_shelf')
    )
    op.create_index(op.f('ix_shelves_id'), 'shelves', ['id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aisle_id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('human_code', sa.String(), nullable=False),
    sa.Column('occupied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aisle_id'], ['aisles.id'], ),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'row_index', 'col_index', name='uq_shelf_row_col')
    )
    op.create_index(op.f('ix_slots_human_code'), 'slots', ['human_code'], unique=True)
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    op.create_index(op.f('ix_slots_occupied'), 'slots', ['occupied'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'OUT_STOCK', 'RESERVED', name='devicestatus'), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('from_slot_id', sa.Integer(), nullable=True),
    sa.Column('to_slot_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CHECK_IN', 'CHECK_OUT', 'MOVE', 'RESERVE', 'RELEASE', name='movementtype'), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['from_slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['to_slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_slots_occupied'), table_name='slots')
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_human_code'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_shelves_id'), table_name='shelves')
    op.drop_table('shelves')
    op.drop_index(op.f('ix_aisles_name'), table_name='aisles')
    op.drop_index(op.f('ix_aisles_id'), table_name='aisles')
    op.drop_table('aisles')
    # ### end Alembic commands ###

